// Deterministic data and scenario for ChronoSat: Temporal Time Machine
import type { TemporalScenario, LearningNode } from '../types/chronosatGame';

export const CHRONOSAT_SCENARIO: TemporalScenario = {
  id: 'bah2026-delta-pass',
  regionName: 'Mahanadi Coastal Delta Basin',
  coordinates: '20°17\'44"N 86°42\'18"E',
  sensorConstellation: 'Multi-Spectral Earth Orbiter (Simulation)',
  temporalGapHours: 48,
  gapLabel: '48 HOURS (2-DAY REVISIT GAP)',
  challengeTrack: 'Bharatiya Antariksh Hackathon 2026 (BAH2026)',
  frames: {
    t0: {
      id: 'T0',
      label: 'FRAME T0 (INITIAL PASS)',
      subLabel: 'Baseline Ground Truth Observation',
      timestamp: '2026-03-12 05:30:00 UTC',
      source: 'Orbiter Sensor Pass A',
      status: 'GROUND_TRUTH',
      sensor: 'Multi-Spectral MSI (10m GSD)',
      resolution: '10m / pixel',
      cloudCover: '14.2%',
      spectralBands: ['B02 (Blue)', 'B03 (Green)', 'B04 (Red)', 'B08 (NIR)'],
      solarAzimuth: '138.4°',
      description: 'Initial optical snapshot showing high-contrast coastline, river delta estuaries, and localized upstream cloud formations heading eastward.'
    },
    intermediate: {
      id: 'INTERMEDIATE',
      label: 'FRAME T+Δ (SYNTHESIZED)',
      subLabel: 'Optical Flow Neural Reconstruction',
      timestamp: '2026-03-13 05:30:00 UTC (+24h)',
      source: 'ChronoSat Temporal Synthesizer (BAH 2026)',
      status: 'SYNTHESIZED',
      sensor: 'Dense Flow Multi-Band Warp',
      resolution: '10m / pixel (Synthesized)',
      cloudCover: '31.8% (Estimated)',
      spectralBands: ['B02-B08 Motion-Compensated Bands'],
      solarAzimuth: '140.1° (Interpolated)',
      flowVectorCount: 14280,
      synthesisConfidence: '91.4% Structural Similarity (SSIM)',
      description: 'Intermediate snapshot generated by ChronoSat deep optical flow interpolation, predicting mid-point cloud front translation and estuarine silt flow.'
    },
    t1: {
      id: 'T1',
      label: 'FRAME T1 (REVISIT PASS)',
      subLabel: 'Subsequent Ground Truth Verification',
      timestamp: '2026-03-14 05:30:00 UTC (+48h)',
      source: 'Orbiter Sensor Pass B',
      status: 'TARGET_TRUTH',
      sensor: 'Multi-Spectral MSI (10m GSD)',
      resolution: '10m / pixel',
      cloudCover: '48.6%',
      spectralBands: ['B02 (Blue)', 'B03 (Green)', 'B04 (Red)', 'B08 (NIR)'],
      solarAzimuth: '141.8°',
      description: 'Revisit satellite snapshot verifying downstream cloud dissipation, shifted sediment plume, and altered tidal boundary after 48-hour orbital cycle.'
    }
  }
};

export const LEARNING_NODES: LearningNode[] = [
  {
    id: 'frame-concept',
    title: 'WHAT IS A SATELLITE FRAME?',
    subtitle: 'Discrete Spatial Raster Snapshot',
    shortDesc: 'A 2D multi-band image captured during an orbital swath pass over a defined geographic bounding box.',
    details: [
      'Earth observation satellites orbit in polar or sun-synchronous trajectories at altitudes between 500km and 800km.',
      'Sensors capture multiple spectral wavelengths simultaneously (visible RGB, near-infrared, and shortwave infrared).',
      'Each raw observation constitutes an instantaneous spatial snapshot fixed in space and time.'
    ],
    icon: 'Layers'
  },
  {
    id: 'gap-concept',
    title: 'WHAT IS THE TEMPORAL GAP?',
    subtitle: 'Orbital Revisit Interval Blindspots',
    shortDesc: 'The time duration between successive satellite passes over the exact same ground coordinates.',
    details: [
      'Standard medium-to-high resolution optical satellites revisit coordinates every 1 to 5 days.',
      'During severe environmental emergencies (floods, wildfire spread, storm surges), ground dynamics evolve in hours.',
      'The temporal gap creates critical observational blindspots where rescue operators lack visual data.'
    ],
    icon: 'Clock'
  },
  {
    id: 'interpolation-concept',
    title: 'WHAT IS TEMPORAL INTERPOLATION?',
    subtitle: 'Motion Vector & Deep Neural Synthesis',
    shortDesc: 'Synthesizing plausible intermediate frames by modeling motion trajectories between existing observations.',
    details: [
      'ChronoSat computes dense optical flow motion fields tracking pixel displacement between Frame T0 and Frame T1.',
      'Neural networks compensate for non-rigid cloud motion, shadows, and spectral reflectance variations.',
      'Intermediate frames provide continuous temporal monitoring without requiring new physical orbital satellites.'
    ],
    icon: 'Zap'
  }
];
